### ISSUE TITLE
Remove footer from sign-in & sign-up pages

### ISSUE THREAD

**Issue by arya56** [HackYourFuture-CPH/rate-my-cv#117]
## User story

**Who:** **As a** **user**

**What:** **I want to** _<see>_
I shouldn't see footer in sign-in and Sign-up pages
**Why:** **so that we can** _<achieve some goal>_
right now catching this url https://rate-my-cv-staging.herokuapp.com/sign-up 
will give you the page with footer.
![image](https://user-images.githubusercontent.com/19622435/107203588-eb47ef80-69fb-11eb-90d8-c4cdbc750561.png)

## Acceptance criteria

**Given** _<user context>_ (example: "as an authenticated user")

**When** _<some action is performed>_ (example: "send a message")

**Then** _<some out outcome(s) should occur>_ (example: "I can read and reply to the message")

## Implementation details

- [You define them here based on the above]

**Comment by dpfernandes** [comment]
Can you add the file URL where you see the footer ?

**Comment by arya56** [comment]
the url added

**Comment by dpfernandes** [comment]
Please consider issues https://github.com/HackYourFuture-CPH/rate-my-cv/issues/122 and https://github.com/HackYourFuture-CPH/rate-my-cv/issues/123 for this.

**Comment by arya56** [comment]
I think this related to footer task and should have been done within that task.
