### ISSUE TITLE
Frontend button

### ISSUE THREAD

**Issue by benna100** [HackYourFuture-CPH/rate-my-cv#13]
## User story

**Who:** **As a** developer

**What:** **I want to** use a button

**Why:** **so that we can** have standardized buttons

## Implementation details

- Create a button that a developer can say is either a primary (orange background color) or secondary button (white backgroundcolor)

**Comment by dpfernandes** [comment]
PR https://github.com/HackYourFuture-CPH/rate-my-cv/pull/53 solved this issue
