### ISSUE TITLE
Fix the signin page

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/rate-my-cv#184]
## User story

**Who:** **As a** user 
**What:** **I want to** be able to register if I am not registered
**Why:** **so that we can** access the app.

## Acceptance criteria

Please check the difference between what's being rendered and the wireframes

<img width="1262" alt="Screenshot 2021-02-21 at 11 18 17" src="https://user-images.githubusercontent.com/6642037/108622187-5d2a2b00-7437-11eb-9776-b03f36bcfa6f.png">
<img width="487" alt="Screenshot 2021-02-21 at 11 17 01" src="https://user-images.githubusercontent.com/6642037/108622190-60251b80-7437-11eb-8f53-5974c78e8350.png">

## Implementation details

Remove footer
Remove login button on top (it should be the header but please confirm)
Add this button 
![image](https://user-images.githubusercontent.com/6642037/108622251-c1e58580-7437-11eb-854c-c521d2d40d65.png)

**Comment by arya56** [comment]
@kamalrsa @dpfernandes  the onSubmit handler needed to be passed from <loginForm> to <useform> and the values should be checked for correct data
