### ISSUE TITLE
Endpoint: POST api/cvs

### ISSUE THREAD

**Issue by benna100** [HackYourFuture-CPH/rate-my-cv#2]
## User story

**Who:** **As a** developer

**What:** **I want to** be able to create a new cv using a POST endpoint

**Why:** **so that we can** add a cv to a user

## Implementation details
- Create the POST endpoint `api/cvs`

Look at the database diagram for details on what fields to add

**Comment by dpfernandes** [comment]
PR https://github.com/HackYourFuture-CPH/rate-my-cv/pull/108 solves this issue
