### ISSUE TITLE
User signup functionality

### ISSUE THREAD

**Issue by benna100** [HackYourFuture-CPH/rate-my-cv#43]
## User story

**Who:** **As a** user

**What:** **I want to** be able to put in my user details

**Why:** **so that we can** create a new user

## Implementation details

- Can first be done when this story is merged: https://github.com/HackYourFuture-CPH/rate-my-cv/issues/42
- Involves taking the data when the signup form is submitted
- Creating a new user in firebase, storing the token in our sql (and adding the database migration for that)
- When the user is created log that user in and redirect to any page
- Ask Niels Schmidt or Victoria from class 13 about this.

**Comment by ember-b-Moss** [comment]
- [ ] update the configuration file for firebase
- [ ] update the database/the user table to have a new collumn for token i have to store
- [ ] when user signs up i have to insert token in database together with all other user data
- [ ] login user to firebase
- [ ] redirect user to any page
