### ISSUE TITLE
Correction of CVS migrations

### ISSUE THREAD

**Issue by Kiran-Serolla** [HackYourFuture-CPH/rate-my-cv#57]
## User story

**Who:** **As a** user_

**What:** **I want to** use the cvs table

**Why:** **so that we can**use the table data

## Acceptance criteria

**Given** _<user context>_ (example: "as an authenticated user")

**When** _<some action is performed>_ (example: "send a message")

**Then** _<some out outcome(s) should occur>_ (example: "I can read and reply to the message")

## Implementation details

- There was an error in the migrations for cvs , the  table.dropColumn('fk_user_id);  was used twice in the drop function.

**Comment by dpfernandes** [comment]
Solved on PR https://github.com/HackYourFuture-CPH/rate-my-cv/pull/62

**Comment by dpfernandes** [comment]
The PR #62 solved the issue.
